### ISSUE TITLE
Modonomicon adds an empty creative tab

### ISSUE THREAD

**Issue by ShelLuser** [klikli-dev/modonomicon#229]
I'm using Modonomicon 1.73.0 on Forge 47.3.0; but I also tested this behavior with the latest NeoForge (time of writing).

The mod creates an empty creative tab for no reason, previous versions added a tab with a debug option but right now there's only a gap. While this doesn't have any direct impact on the game itself I still consider this highly annoying because it always manages to visually distract me.

Seriously: I'd rather have a debug tab which contains a useless option for me rather than seeing a gap on my screen ;)

I use Modonomicon / Occultism in a mod collection of my own but already conducted tests: the moment I add Occultism to a new 1.20.1 installation the Modonomicon mod immediately creates this gap. I also tried to remove and thus recreate the config file but that didn't do anything for me either.

**Comment by klikli-dev** [comment]
Hmm this is a side effect of the debug contents being excluded.
The creative tab exists as a fallback if a mod creator does not provide a target creative tab. If all mods provide a creative tab, the modonomicon one is empty.

I will ask mod in the mod loader discords if conditional creative tabs are feasible without too much mixin use. 
Otherwise I can entirely remove the creative tab, but that breaks backwards compatibility (at least in terms of expected behaviour by mod devs) so it is not a great solution imo.

EDIT: I just realized the other option is to just always display modonomicons in that tab (+ additionally in the target tab). That might be a useful improvement without breaking anything.
