### ISSUE TITLE
Formatting Code for text with double outline

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#241]
**Is your feature request related to a problem? Please describe.**
With the addition of Glow Ink, you can now make signs glow, which gives the text a double outline.
This is great for text you want to emphasize, or that would otherwise be hard to read because of text color or similar.

**Describe the solution you'd like**
A formatting code that makes the text have a double outline, similar to bold/italic text.

**Additional context**
![image](https://github.com/user-attachments/assets/1fdec64a-8500-4f52-8812-27372de6e993)

**Comment by klikli-dev** [comment]
Do you have ideas for the syntax? @DaFuqs 

Basically we have two options: A custom delimeter like for italics/bold, or a link-based syntax like the colors.

**Comment by klikli-dev** [comment]
Hmm as it turns out it may not be as easy. 
The glow ink is not actually a minecraft text rendering via the component system, rather it is something used only by the sign, where it manually calls a special font method that draws an outline.

Currently the modonomicon rendering system can only cover styles that minecraft can also render e.g. in the chat (that can be represented in the component system).

**Comment by DaFuqs** [comment]
Oh course it is something weird again, otherwise it would be too easy. Thanks, Mojang!

In this case feel free to disregard the suggestion. While it could be a nice feature I do not think the reward matches the effort required to add it.

**Comment by klikli-dev** [comment]
Yeah it's an odd choice to not just make that a render mode of the component system :( 
I will close this then, if someone comes up with an idea we can revisit it
