### ISSUE TITLE
Some thin blocks don't render in multiblock preview

### ISSUE THREAD

**Issue by Eqis-Edu** [klikli-dev/modonomicon#260]
**Describe the bug**
Iron bars, glass pane and chain is not rendered in world preview, only appear inside the book.

Note: colored glass panes are shown.

**To Reproduce**
1. Have multiblock in modonomicon with one of these blocks (used occultism last pentacle)
2. Click Eye Button
3. Place in world

**Expected behavior**
Render these blocks in placed preview

**Screenshots**
![2024-10-29_09 25 19](https://github.com/user-attachments/assets/9a814872-6302-4413-80cc-f862bbec3085)

**System (please complete the following information):**
- Modonomicon Version: 1.108.1
- OS: Windows 10
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: 
![image](https://github.com/user-attachments/assets/0939c4b2-c604-4d3a-af2d-af1b2cffafec)

**Comment by klikli-dev** [comment]
Thanks for reporting!
I wonder why these are not rendering, as currently the rendering uses the vanilla block renderer for both places. I need to do some testing, maybe it is about the render state setup

**Comment by klikli-dev** [comment]
On second thought, the colored glass panes might be hint that the render type is different and somehow does not render cutout (only "true" transparency)

Yes, the problem is the transparency rendering of the multiblock preview. It adds "enableBlend" and an alpha value to the render types. For cutout that leads to no rendering at all. I will check with smarter people if this can be counteracted

**Comment by klikli-dev** [comment]
Next update will fix this, but e.g. glass panes are not great blocks to use in multiblocks as they are very dependent on blockstate. Their default blockstate basically just renders one 3d pixel at the top and one at the bottom
