### ISSUE TITLE
Server crash on joining. Was asked to post it here

### ISSUE THREAD

**Issue by Neverlight-Jyria** [klikli-dev/modonomicon#47]
**Describe the bug**
Crashlog on entering world

**To Reproduce**
I loaded up the game and joined the server, the server crashed

**System (please complete the following information):**
- Modonomicon Version: 1.4.0
- OS: Linux
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: TNP Limitless 6 V1.1.1

**Additional context**
[crash-2022-10-17_17.37.07-server.txt](https://github.com/klikli-dev/modonomicon/files/9803229/crash-2022-10-17_17.37.07-server.txt)

**Comment by klikli-dev** [comment]
@JyriaLycion thank you for reporting this!
Can you try with just modonomicon + dependencies on your client and server? And in reverse, try in your current setup, but without modonomicon (and mods that rely on modonomicon)? 

This does not reproduce for me with just modo+deps. 

Additionally the crash log says ` Cannot read field "f_9742_" because "java.util.function.Supplier.get().f_8906_"`, that field is the field that holds the connection and is forge, not from modonomicon. 
It looks a bit like modonomicon is just the unlucky first mod that sends a network packet after something else has gone wrong.

This means it could be an adverse mod interaction, or another mod causing it. To fix it we definitely need to narrow it down to the smallest possible setup where it happens

**Comment by klikli-dev** [comment]
Closing this as stale. Please comment here so I can reopen it if it is still a current issue
