### ISSUE TITLE
java.lang.reflect.invocationtargetexception: null

### ISSUE THREAD

**Issue by MadDog84** [klikli-dev/modonomicon#68]
Hi ! I was trying to install Occultism so i downloaded and installed all of the dependencies but im getting this error when launching Mc forge 

"java.lang.reflect.invocationtargetexception: null"

I only have the mods needed for Occultism. And i'm on minecrafy 1.19.2 

I joined the two logs ^^

Thanks for your works btw your mod looks amazing :-)

[crash-2022-11-11_09.21.46-fml.txt](https://github.com/klikli-dev/modonomicon/files/9988397/crash-2022-11-11_09.21.46-fml.txt)
[latest.log](https://github.com/klikli-dev/modonomicon/files/9988406/latest.log
![issues](https://user-images.githubusercontent.com/24478142/201297875-42850c50-ad26-4b1d-926c-1669b46940ae.jpg)
)

**Comment by klikli-dev** [comment]
You seem to be on an outdated forge version. The underlying issue is `java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/AdvancementEvent$AdvancementEarnEvent`, and `AdvancementEarnEvent` is not present in older versions of forge for 1.19.2

Please use your launcher to update to latest forge and it should work - feel free to ping me if issues remain after that so I can reopen
